apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image }}
    imagePullPolicy: IfNotPresent
    name: kamper
    resources: {}
    stdin: true
    stdinOnce: true
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock