apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - nodePort: 30010
    port: {{ .Values.publicPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    run: kamper
  sessionAffinity: None
  type: LoadBalancer